name: Get status code
on:
  schedule:
    - cron: 0 2 * * 5-6
jobs:
   getcode:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up PHP8.0'
        uses: shivammathur/setup-php@v2
        with:
           php-version: '8.0'
      - name: 'Working'
        run: php ./index.php ${{ secrets.DOMAIN }}
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 网站III${{ secrets.NAME }}III->>>${{ secrets.DOMAIN }}状态报告
          body: file://email.txt
          to: ${{ secrets.MAIL_RECEIVER }}
          from: GitHub Actions
          content_type: text/plain
